#!/usr/bin/env python3
"""Build the shared local-AI instruction bundle from marked policy rules."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
TARGET = Path("agents/instructions/standard.md")
SOURCES = (
    (
        "response-clarity",
        "Response Clarity And Meaning Preservation",
        Path("agents/policies/baseline/response-clarity.md"),
    ),
    (
        "competence-routing",
        "Competence-First Delegation",
        Path("agents/policies/harness/competence-first-delegation.md"),
    ),
    (
        "operator-context-continuity",
        "Operator Context Continuity",
        Path("agents/policies/harness/operator-briefing-and-review-receipts.md"),
    ),
    (
        "code-quality",
        "Code Quality",
        Path("agents/policies/baseline/code-quality.md"),
    ),
)
HEADER = (
    "<!-- Generated by scripts/render_global_agent_instructions.py. "
    "Do not edit directly. -->\n"
    "<!-- Shared instructions for local AI runtimes; "
    "install only approved marked regions. -->"
)


def extract_rules(text: str, key: str, source: Path) -> str:
    start = f"<!-- ai-assets:{key}:start -->"
    end = f"<!-- ai-assets:{key}:end -->"
    lines = text.splitlines()
    if lines.count(start) != 1 or lines.count(end) != 1:
        raise ValueError(f"{source}: expected exactly one {key} marker pair")
    first, last = lines.index(start), lines.index(end)
    if first >= last:
        raise ValueError(f"{source}: reversed {key} markers")
    rules = "\n".join(lines[first + 1 : last]).strip("\n")
    if not rules.strip():
        raise ValueError(f"{source}: empty {key} rules")
    if "<!-- ai-assets:" in rules:
        raise ValueError(f"{source}: nested managed marker in {key} rules")
    return rules


def render(root: Path = REPOSITORY_ROOT) -> str:
    blocks = []
    for key, title, relative in SOURCES:
        source = root / relative
        rules = extract_rules(source.read_text(encoding="utf-8"), key, relative)
        blocks.append(
            f"<!-- ai-assets:{key}:start -->\n\n"
            f"## {title}\n\n{rules}\n\n"
            f"<!-- ai-assets:{key}:end -->"
        )
    return HEADER + "\n\n" + "\n\n".join(blocks) + "\n"


def main(
    argv: Sequence[str] | None = None, *, root: Path = REPOSITORY_ROOT
) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in bundle is stale"
    )
    args = parser.parse_args(argv)
    try:
        expected = render(root)
        target = root / TARGET
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != expected:
                print(
                    f"{TARGET} is missing or stale; run "
                    "python3 scripts/render_global_agent_instructions.py",
                    file=sys.stderr,
                )
                return 1
            print(f"{TARGET} is current")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
            print(f"Generated {TARGET}")
    except (OSError, UnicodeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
